### ISSUE TITLE
Nuget package using GitHub actions

### ISSUE THREAD

**Issue by IngvarX** [samuelneff/MimeTypeMap#100]
Hello! 

Thanks for you library, I found it useful. But the only problem it's not published to Nuget so I can't integrate it into my app easily. What do you think about publishing packages using GitHub action? Here is link: https://github.com/marketplace/actions/publish-nuget All you need is to login on https://www.nuget.org/ and create key, add yaml file with configuration to your solution. If it's not fine for you I can upload latest package to Nuget but it will be manual approach.

**Comment by samuelneff** [comment]
It's up!

https://www.nuget.org/packages/MimeTypeMapOfficial

I updated Readme to point to this one.

I don't know if the action is working. This one I uploaded manually. Perhaps the first time it has to be manual. The action ran when I added it but it didn't create the package. I'll try the action again for next push.

Thanks for the extra info. I'm happy to finally have this done.

**Comment by samuelneff** [comment]
@IngvarX I bumped the version to 1.0.5 and GitHub says it ran the action, but no new version shows on NuGet. Any idea how to debug this thing?

**Comment by IngvarX** [comment]
This is how I added same action to one of my repos:
1) I opened add API key page and selected my package in Available Packages:
![image](https://user-images.githubusercontent.com/10050680/85429883-0a3a6400-b588-11ea-9098-c96e5adce438.png)
2) Copied generated key and inserted it here:
![image](https://user-images.githubusercontent.com/10050680/85430016-3eae2000-b588-11ea-848a-3d66e4703ceb.png)

I checked your action build and found this line [here:](https://github.com/samuelneff/MimeTypeMap/runs/793499257?check_suite_focus=true)

> Successfully created package '/home/runner/work/MimeTypeMap/MimeTypeMap/MimeTypeMap.1.0.5.nupkg'.

I suppose there is name conflict. `MimeTypeMap` is not a name of your package (not sure nut maybe it should be `MimeTypeMapOfficial`), probably you should change `PackageId`?

**Comment by ferronsw** [comment]
This package isn't working for .Net Core, but it should right? Maybe a settings that's not correct?

**Comment by samuelneff** [comment]
`1.0.7` had a problem packaging but `1.0.8` fixes it. It should work for .net core 2.x and 3.x, as well as .NET 4.x and 2.0.
