### ISSUE TITLE
broken nuget package

### ISSUE THREAD

**Issue by f2calv** [samuelneff/MimeTypeMap#101]
Seems your pipeline is brokem as the [Nuget release 1.0.7](https://www.nuget.org/packages/MimeTypeMapOfficial/1.0.7) doesn't contain any compiled libraries, only the source code - as you can see via [NugetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer).

![image](https://user-images.githubusercontent.com/16097639/86505428-ac4a1f80-bdc4-11ea-9936-289f7b221e53.png)

Below is the folder layout of a working nuget package;
![image](https://user-images.githubusercontent.com/16097639/86505475-60e44100-bdc5-11ea-8870-14f3bfc41f92.png)

**Comment by samuelneff** [comment]
Thank you for letting me know. `1.0.8` has the binaries in it. Please let me know if this did not actually fix it.
