### ISSUE TITLE
Content-Type: application/x-msdos-program

### ISSUE THREAD

**Issue by Richard-BM** [samuelneff/MimeTypeMap#102]
Hello, I received an error message when I tried to download a file because the content type (application/x-msdos-program) does not exist in this project yet. For detailed information, you can have a look at the screenshots below. Expected was an .exe extension.
![Bildschirmfoto 2020-07-06 um 11 41 40](https://user-images.githubusercontent.com/28219287/86580134-98e2b400-bf7e-11ea-9046-40c6ce7c2284.png)
![Bildschirmfoto 2020-07-06 um 11 40 16](https://user-images.githubusercontent.com/28219287/86580138-9a13e100-bf7e-11ea-90a6-bcb522bbf232.png)

**Comment by samuelneff** [comment]
Thank you for pointing this one out. I'll add it as a mapping from `application/x-msdos-program` to `.exe`. The reverse will not be mapped though because `.exe` currently maps to `application/vnd.microsoft.portable-executable`.

I'll update this thread once complete (planned for tonight).

**Comment by samuelneff** [comment]
Added unidirectional mapping just now and published to NuGet as 1.0.11. Thank you for pointing out the missing mapping.
