### ISSUE TITLE
Requested mime type is not registered: audio/mp4

### ISSUE THREAD

**Issue by quaerendo0** [samuelneff/MimeTypeMap#105]
It is a well-known type from what I get but MimeTypeMap does not recognise it

**Comment by samuelneff** [comment]
`MimeTypeMap` is primarily a mapping of file extensions to mime types. `.mp4` maps to `video/mp4`. I'm not aware of a file extension that exclusively maps to `audio/mp4`. Is there one that isn't also used for something else more often?

We can provide only a reverse mapping, from `audio/mp4` to `.m4a`. Would that be useful?

**Comment by quaerendo0** [comment]
Absolutely! In fact, this was the type of file that I worked with and when I got this error in particular. Would you be so kind to add it, please?

**Comment by samuelneff** [comment]
Mapping for `audio/mp4` to `.m4a` added and new package 1.0.10 published to NuGet. Thanks for pointing out this missing mapping.
