### ISSUE TITLE
Mime type not recognize 

### ISSUE THREAD

**Issue by JoseRodriguezLopez** [samuelneff/MimeTypeMap#109]
Hi, I am having problems with extension "application/vnd.ms-outlook". I reviewed class MimeTypeMap.cs and it is there but for some reason I am getting an exception "Requested mime type is not registered: application/vnd.ms-outlook".

**Comment by samuelneff** [comment]
Can you share a short snippet of code? Did you copy and paste the error exactly or did you retype it into GitHub?

**Comment by JoseRodriguezLopez** [comment]
`private static string GetExtension(string contentType)
        {
            return MimeTypes.MimeTypeMap.GetExtension(contentType);
        }`

I confirm you that I copied and pasted the error from VS. Thanks in advance!

**Comment by samuelneff** [comment]
Where exactly does `contentType` come from? User provided? Do you get this error if you try other valid mime types?

**Comment by samuelneff** [comment]
Can you set a breakpoint inside `GetExtension` and see what the difference/issue is when stepping through?

**Comment by JoseRodriguezLopez** [comment]
![image](https://user-images.githubusercontent.com/61020588/95895746-5e8c6e00-0d48-11eb-85ab-6e79100e0821.png)

**Comment by JoseRodriguezLopez** [comment]
The content type come from a web client response headers, specifically from the Content-Type. It works with other extensions, I am getting the error just with "application/vnd.ms-outlook."

**Comment by samuelneff** [comment]
I've thought about this issue a lot and am sorry to say I can't reproduce the issue or come up with an explanation or fix.
