### ISSUE TITLE
GetExtension should return null in case it didn't find the extension

### ISSUE THREAD

**Issue by HunteRoi** [samuelneff/MimeTypeMap#113]
This is not "mandatory" but would lead to a more friendly approach for a new user that comes across your package. Obviously, if the data is not found, you should never return a value (even if an empty string) as it may lead to strange behavior or misunderstanding.

I would highly recommend to introduce this breaking change in your library:

```diff
public static string GetExtension(string mimeType, bool throwErrorIfNotFound = true)
{
     ...

-    return string.Empty;
+    return null;
}
```

**Comment by HunteRoi** [comment]
In addition to this, I would recommend anyone making checks against a string to use the extension methods provided to that use:
- [String.IsNullOrEmpty(String)](https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorempty?view=netstandard-2.1)
- [String.IsNullOrWhiteSpace(String)](https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=netstandard-2.1)

**Comment by samuelneff** [comment]
I'm not going to introduce what could easily be a breaking change for everybody. Sorry. We are introducing a `TryGetExtension` method in another PR which should satisfy your needs.

**Comment by HunteRoi** [comment]
Can you link that pull request ? I'd like to take a look at the code. I don't see anything related to that but it's a good idea to introduce a `TryGetExtension` too!

**Comment by samuelneff** [comment]
It's now been merged. Take a look at the updated code that includes `TryGetExtension`. NuGet also updated.
