### ISSUE TITLE
NuGet package not updated

### ISSUE THREAD

**Issue by HunteRoi** [samuelneff/MimeTypeMap#115]
Hello there!

It seems that 3 days ago, the NuGet package was updated. As you stated in #113, you also included a `TryGetExtension` method in your codebase. Unfortunately, it does not seem to be anywhere on Github nor in the package version 1.0.12.

Here are a few screenshots:

![image](https://user-images.githubusercontent.com/32441291/102067220-18f92980-3dfb-11eb-8290-c57b47cde558.png)
As you can see, it is the latest version available and there are no methods added nor XML documentation (even though `TryGetMimeType` was added with PR #114).

![image](https://user-images.githubusercontent.com/32441291/102067493-755c4900-3dfb-11eb-9c42-652910cc88cd.png)
Here I cannot find the `TryGetExtension` method you were talking about in issue #113 .

![image](https://user-images.githubusercontent.com/32441291/102068033-3aa6e080-3dfc-11eb-932d-0f5d9a9ee69c.png)

**Comment by samuelneff** [comment]
Thank you for pointing that out. I'll get another update out later today.

**Comment by samuelneff** [comment]
`1.0.14` now available. https://www.nuget.org/packages/MimeTypeMapOfficial/

**Comment by HunteRoi** [comment]
No problem dude! Have a happy holidays season! Stay safe 😄
