### ISSUE TITLE
Recent commit introduced breaking changes and ambigous behavior

### ISSUE THREAD

**Issue by lajjne** [samuelneff/MimeTypeMap#118]
Commit https://github.com/samuelneff/MimeTypeMap/commit/ace145c93cf87d2216617116567ddee551fde22f added some breaking changes and also introduced some ambiguous behavior.

### Breaking

`GetMimeType("")` previously returned "application/octet-stream" but now throws `ArgumentNullException`.

### Ambiguous

`GetMimeType` used to take a file extension as input but now takes a file name _or_ file extension. This can lead to some cases where it is not clear what the expected output should be.

Consider for example the string "gif". This could be a valid filename for a file without file extension and should in that case return "application/octet-stream". But it could also be interpreted as the file extension ".gif". To remove this ambiguity I suggest reverting to the previous behavior of expecting a file extension only. 

Another option could be to change `GetMimeType` to expect a path string instead and then use `System.IO.Path.GetExtension(path)` to get the file extension before looking in the internal dictionary. 

```
public static string GetMimeType(string path) {
    if (path == null) {
        throw new ArgumentNullException(nameof(path));
    }
    if (path != string.Empty && Path.GetFileName(path) == string.Empty) {
        throw new ArgumentException($"{path} is not a file path", nameof(path));
    }
    var ext = Path.GetExtension(path);
    return MimeTypeMap.TryGetMimeType(ext, out var result) ? result : DefaultMimeType;
}        
```

The following examples would then all be valid input:

* `GetMimeType(null)` => throws ArgumentNullException
* `GetMimeType("")` => "application/octet-stream"
* `GetMimeType(".")` => "application/octet-stream"
* `GetMimeType("gif")` => "application/octet-stream"
* `GetMimeType(".gif")` => "image/gif"
* `GetMimeType("test.gif")` => "image/gif"
* `GetMimeType("/test/image.gif")` => "image/gif"
* `GetMimeType(@"C:\test")` => "application/octet-stream"
* `GetMimeType(@"C:\test\")` => throws ArgumentException
* `GetMimeType(@"C:\test\image.gif")` => "image/gif"

**Comment by samuelneff** [comment]
I've restored the previous behavior of returning `application/octet-stream` for an empty string and no longer throwing `ArgumentNullException` in this case.

Other changes would equally be breaking changes. Particularly getting mime type for an extension without a dot IMO should return the proper mime type. Changing that would be a bigger breaking change.

Thanks for bringing this to my attention.
