### ISSUE TITLE
Create strongname version of nuget package

### ISSUE THREAD

**Issue by sjoerd222888** [samuelneff/MimeTypeMap#15]
Would it also be possible to have your library as strong name nuget package?

**Comment by samuelneff** [comment]
I don't mind doing this. Another user added the nuget package for me through a pull request. I've never used Nuget myself (I don't do any new .NET development anymore--only maintenance).

https://github.com/samuelneff/MimeTypeMap/pull/5

When I find time I'll look into what it takes to create a strongly named package and update it.

**Comment by samuelneff** [comment]
I realize this is 10 months old now, and just to update anyone reading the issue, it has not been a priority for me.

**Comment by sjoerd222888** [comment]
I have sent an email to the nuget package maintainer and asked whether he could create a strongname version. I did not receive an answers, I guess it is also no priority for him.
