### ISSUE TITLE
Core CLR compatibility

### ISSUE THREAD

**Issue by fredgate** [samuelneff/MimeTypeMap#29]
The library should support Core CLR and ported to .Net Platform 5.4.

**Comment by samuelneff** [comment]
Can you clarify what exactly you're asking for? What changes are required to fulfill this request?

**Comment by 0xdeafcafe** [comment]
I've already done it over here: https://github.com/HelmGlobal/MimeTypeMap. I didn't do a pull request as didn't update the docs project to use the updated code.

**Comment by samuelneff** [comment]
Thanks. Looking at your fork it seems both the current and a core project could both be supported with separate project/sln files.

Is the `project.json` file necessary for core or did you add it for something else?

Sam

**Comment by 0xdeafcafe** [comment]
That's required currently. When the runtime hits RTM, they are going to merge it into the `xproj` file.
