### ISSUE TITLE
Provide strong assembly name

### ISSUE THREAD

**Issue by Pzixel** [samuelneff/MimeTypeMap#34]
Currently assembly could not be used with strong-typed libraries. It's easy to fix it, but it's on you.

Hmm, I found that similar request is open from sept 2015. It's 5 minutes to do, just create an snk file and add it in project properties.

**Comment by samuelneff** [comment]
I don't provide a binary release, only source, so as I understand it the strong naming is not on my end to release. It would only apply if I was providing a binary release.

If I'm misunderstanding the request, please clarify. I'm happy to do anything reasonable that helps out and doesn't affect other users.

**Comment by Pzixel** [comment]
Here is a NuGet package where you are specified as an author. So this is why I ask for it. If you are not, then I think I should fork it and create another one, becuase in this case we both don't know who is responsible for this package.

**Comment by samuelneff** [comment]
Thanks for explaining. I actually don't manage the NuGet repository. You are free to create your own strong named version for your use.
