### ISSUE TITLE
You should deliver this as source, not dll

### ISSUE THREAD

**Issue by rhyous** [samuelneff/MimeTypeMap#35]
Saw your post http://stackoverflow.com/questions/1029740/get-mime-type-from-filename-extension/14108040#14108040.

Getting your single file as Source from NuGet would be vastly better than as a dll. I recently starting providing NuGet packages for source files instead of dll files and it is quite useful.
http://www.rhyous.com/2016/03/03/nuget-for-source-using-add-as-link-1

**Comment by samuelneff** [comment]
Thanks for the comment. I realize it's not clear but I'm actually not involved in the NuGet package. Someone else manages that and I merge his package changes as he submits them.
