### ISSUE TITLE
Enhancement | Have static content type class

### ISSUE THREAD

**Issue by aroemen** [samuelneff/MimeTypeMap#52]
It would be nice to have the string values (IE...application/json) of the content type setup in a static class. This would be handy to have for validating without having magic strings throughout the code.

**Comment by samuelneff** [comment]
Good point. I'll make the change next time I'm working on the project.

**Comment by wagesj45** [comment]
@aroemen would [my project](https://github.com/wagesj45/MimeTypeList) fit the bill for what you're requesting? It is based on this project and is a static mapping.
