### ISSUE TITLE
missing "audio/mp3" type

### ISSUE THREAD

**Issue by shizenghua** [samuelneff/MimeTypeMap#62]
missing "audio/mp3" type.
 repeat "application/acad"  type.

**Comment by samuelneff** [comment]
I'll fix the acad duplicate today, thank you for pointing that out.

audio/mp3 is not a correct mime type. audio/mpeg is correct and listed. See https://tools.ietf.org/html/rfc3003 and not that it uses the terms "Audio layer of Mpeg-1 and Mpeg-2" which is mp3, see https://en.m.wikipedia.org/wiki/MP3.

**Comment by samuelneff** [comment]
Acad duplicate has been addressed. Thanks again for pointing that out.
