### ISSUE TITLE
.zip mimetype is not correct

### ISSUE THREAD

**Issue by jadacyrus** [samuelneff/MimeTypeMap#7]
.zip should be application/zip , not application/x-zip-compressed according to IANA registered types. See here (http://www.iana.org/assignments/media-types/application/zip) and here (http://www.iana.org/assignments/media-types/media-types.xhtml)

**Comment by samuelneff** [comment]
Thanks for pointing it out. I'll correct it the next time I make updates.

**Comment by samuelneff** [comment]
Fixed
