### ISSUE TITLE
Update for the nuget package

### ISSUE THREAD

**Issue by dodbrian** [samuelneff/MimeTypeMap#70]
Please update the nuget-package to catch up with the latest version, including support for .NET Core

**Comment by jackfacts** [comment]
I spoke with Samuel, and he does not have control over the NuGet. I also emailed the maintainer of the NuGet and he was unresponsive. Maybe a little more noise would help the NuGet updated.

**Comment by dodbrian** [comment]
As a last resort we could publish an alternative nuget package and make it official

**Comment by neville-nazerane** [comment]
An alternate nuget has been created: MediaTypeMap.Core
