### ISSUE TITLE
Please update Assembly and Nuget versions.

### ISSUE THREAD

**Issue by zbarrier** [samuelneff/MimeTypeMap#73]
https://github.com/samuelneff/MimeTypeMap/blob/ffbb2d45e3ef66b34a6596779218bba99b0d0f0f/src/MimeTypes/MimeTypes.csproj#L15

**Comment by ryanbuening** [comment]
@zbarrier see https://www.nuget.org/packages/MediaTypeMap.Core

**Comment by zbarrier** [comment]
The nuget version and assembly version differ.  The .csproj has older version.  When using this in a asp.net project, it throws an exception looking for the version referenced in the .csproj.

**Comment by samuelneff** [comment]
I didn't create or manage the nuget package.
