### ISSUE TITLE
Mime Type for .exe files

### ISSUE THREAD

**Issue by racor100** [samuelneff/MimeTypeMap#90]
Using Microsoft's urlmon.dll to identify mime types will give you 'application/x-msdownload' for .exe files in Visual Studio 2019, but according to your mapping .exe files will give us 'application/octet-stream'.

**Comment by samuelneff** [comment]
Looks like the registered mime type is actually `application/vnd.microsoft.portable-executable`. I'll make the change.

https://www.iana.org/assignments/media-types/application/vnd.microsoft.portable-executable

**Comment by samuelneff** [comment]
Updated
