### ISSUE TITLE
NU1701 returned on NUGet package in .Net Core 3.1, but functionality is perfect

### ISSUE THREAD

**Issue by burkenyo** [samuelneff/MimeTypeMap#93]
When referencing the NUGet package in a .Net Core 3.1 project, the NU1701 warning is recieved:

`warning NU1701: Package 'MediaTypeMap 2.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.`

This class works without issue; is it possible to have the NUGet package ”officially” support .net core 3.1?

**Comment by markusschaber** [comment]
Just as a hint: There's a package MediaTypeMap.Core which works on .NET Core:
https://www.nuget.org/packages/MediaTypeMap.Core/

**Comment by burkenyo** [comment]
That's very helpful, thanks!

**Comment by samuelneff** [comment]
None of the nuget packages are officially related to this repo. They're all published by 3rd parties.

@markusschaber Thank you for pointing to the alternate published package.

**Comment by markusschaber** [comment]
@samuelneff Would you be interested in publishing "official" NuGet Packages?

**Comment by samuelneff** [comment]
@markusschaber I'm happy to designate one as official and link to it from the readme, but I'd be looking for someone else to commit to maintaining it (the nuget package, not this repo). I haven't done any .NET development myself in about five years.

**Comment by markusschaber** [comment]
Thanks for letting us know. I'm not in the position to make such a commitment right now, but that situation may change in a few weeks. But maybe one of the other publishers steps up and applies for the "official" signet. :-)
